"""initial migration

Revision ID: fea2c7d30b9f
Revises: 
Create Date: 2024-06-29 19:55:51.542455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fea2c7d30b9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('by_user', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['by_user'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('by_user')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
